### ISSUE TITLE
Prerequisites

### ISSUE THREAD

**Issue by hollenberry** [satelliteworkshops/electron-weather#3]
To be filled in (please edit!) with pre-reqs for setting up Electron/Node/etc. (this will be reproduced and added to the instructions for Exercise 1). 

@nathos you have most of this produced already, right?

Just found it in the other thread 😄 ! Looks awesome. 

@hectorsector this is where those pre-reqs can be found and easily pulled when it's time. Does that work? Or should we move it somewhere else, too?

**Comment by nathos** [comment]
> Or should we move it somewhere else, too?

@hollenberry let's put them right in the README too. I'll open a PR first thing in the morning.

**Comment by hectorsector** [comment]
I vote for the README!
